version: 2
jobs:
    doctor_and_build:
        docker:
            - image: cirrusci/flutter
        steps:
            - checkout
            - run: flutter doctor
            - run: flutter -v build apk

workflows:
    version: 2
    doctor__build:
        jobs:
            - doctor_and_build
